config/routes.rb
MusicianRights::Application.routes.draw do
  root :to => "pages#home"
  get '/home' => "pages#home"
  get '/about' => "pages#about"
  get '/members' => "pages#members"
  get '/admin' => "sessions#new"
  get '/donate' => "pages#donate"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  get '/users/panel' => "users#panel"
  match 'csv' => 'users#export_csv', :as => :csv
  resources :users, only: [:new, :create]
  resources :events, only: [:new, :create, :destroy]
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :title, :location, :time, :details, :date, :button_url
end

app/models/mail_chimp.rb
class MailChimp
  include Hominid

  def self.add_user(user)
    h = Hominid::API.new('91f455bf0d3448173043fd334cbec463-us7')
    h.list_subscribe('61d4987e01', user.email, {'FNAME' => user.first_name, 'LNAME' => user.last_name}, 'html', false, true, true, false)
  end

  def self.unsubscribe_user(user)
    h = Hominid::API.new(MAIL_CHIMP[Rails.env]['api_key'])
    h.list_unsubscribe(MAIL_CHIMP[Rails.env]['subscriber_list'], user.email)
  end

end

app/models/pages.rb
class Pages < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :count, :email, :zipcode, :band, :opt_out
  validates_uniqueness_of :email, message: "An account already exists with this email"
  validates_presence_of :first_name, :last_name, :email, :zipcode
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  # validates_format_of :zipcode, :with => /\w{5}/, :message => "should be in the form 12345"

	def create_user_record_in_mailchimp
		begin
			MailChimp.add_user(self)
		rescue => e
			e.message
		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :admin?

  private

  def admin?
  	session[:password] == 'Lovelife123'
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	def create
		Event.create(params[:event])
    redirect_to users_panel_path
	end	
	
	def destroy
	    @event = Event.find(params[:id])
	    @event.destroy
	    respond_to do |format|
	      format.html { redirect_to users_panel_path }
	    end
	  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		events_list = Event.all.sort_by &:date
		@events = events_list.reverse
		@user = User.new
	end

	def donate
	end

	def about
	end

	def members
		@users = User.where(opt_out: 'false').order('created_at DESC')
		@new_user = User.new
		@flash = params[:flash].to_s
		@count = User.all.length
		@type = params[:user_type].to_s
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  session[:password] = params[:password]
	  flash[:notice] = "Successfully logged in"
	  redirect_to users_panel_path
	end

	def destroy
	  reset_session
	  flash[:notice] = "Successfully logged out"
	  redirect_to home_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		form = params[:user]
		@user = User.create(first_name: form[:first_name],
												last_name: form[:last_name],
												email: form[:email],
												opt_out: form[:opt_out],
												zipcode: form[:zipcode],
												band: form[:band],
												count: User.all.length+1 )
	  respond_to do |format|
	    if @user.save 
	    	if @user.create_user_record_in_mailchimp
	      	format.json { render json: @user }
	      else
		      format.json { render json: "Please use a valid email", status: :unprocessable_entity }
		    end
	    else
	      format.json { render json: @user.errors.full_messages, status: :unprocessable_entity }
	    end
	  end
	end

	def panel
		@new_event = Event.new
		@events = Event.all
	end

	def export_csv
		@users = User.all
    user_csv = CSV.generate do |csv|
      csv << ["First Name", "Last Name", "Zipcode", "Band", "Email", "Opt Out"]
      @users.each do |user|
        csv << [user.first_name, user.last_name, user.zipcode, user.band, user.email, user.opt_out]
      end
		end
		send_data(user_csv, :type => 'test/csv', :filename => 'user_list.csv') 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.haml
.footer.expand
	.foot_box
		.sitemap
			Site Map
			%ul
				%a{"href" => "/"}
					%li
						Home
				%a{"href" => "/members"}
					%li
						Members
				%a{"href" => "/donate"}
					%li
						Donate
				%a{"href" => "/about"}
					%li
						About
				%a{"href" => "mailto:davina.amiri@gmail.com"}
					%li
						Contact
				%a{"href" => "/admin"}
					%li
						Admin
			%p
				DISCLAIMER - MusicianRights.org is not a substitute for legal advice.
				%br
				Please contact an attorney for legal questions.
		.contact
			%p
				<span id="foot_title">Musician Rights</span>
				%br
				349 Fifth Avenue
				%br
				New York, NY 10016

		.copyright
			&#174;2013 Musician Rights. 
			All rights reserved.

app/views/layouts/_header.html.haml
%header.expand
	.container
		.logo
			%a{"href" => "/"}
				=image_tag "logo_one.png"
			- flash.each do |name, msg|
				= content_tag :div, msg, class: name
		.nav_bar
			%ul
				%a{"href" => "/members"}
					%li
						Members
				%a{"href" => "/donate"}
					%li
						Donate
				%a{"href" => "/about"}
					%li
						About
				- if admin?
					= link_to 'Admin Panel', users_panel_path
					= link_to 'Logout', logout_path
		- if @flash
			.flash
				= @flash
		.flex2
			.text
				Join The 
				%br Conversation
			%a{"href" => "https://www.facebook.com/pages/Musician-Rights/123687557816878"}
				%i.icon-facebook
			%a{"href" => "https://twitter.com/MusicianRights"}
				%i.icon-twitter

app/views/layouts/_nav.html.haml
.sign_up.expand
	.container
		.join
			Join Now
		.copy
			We Are Growing a Movement.
			&nbsp
			Be Apart of It!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class=""> <!--<![endif]-->
<head>
	<title>MusicianRights</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width; initial-scale=1.0;">
	<style type="text/css">
	@-moz-document url-prefix() {
		h1 {
		}
	}
	</style>
	<script src="http://malsup.github.com/jquery.form.js"></script>
</head>
<body>
	<%= yield %>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/_facebook.html.erb
<iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fpages%2FMusician-Rights%2F123687557816878&amp;width=345&amp;height=558&amp;show_faces=true&amp;colorscheme=light&amp;stream=true&amp;show_border=true&amp;header=false&amp;appId=165808553601915" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:325px; height:558px;" allowTransparency="true"></iframe>

app/views/pages/_lovers.html.haml
.lovers_bx
	.top
		%h1
			Music Lover’s Statement of Support
		%p
			I am joining this movement because I believe that if Musicians unite to support the Musician Rights Memo, we will create a new standard in the music industry where MUSICIAN'S COME FIRST!
	.body.r_lovepop
		%h3
			Definitions:
		%ul
			%li
				<span id="def">Music Lover</span> - One who garners an overwhelming feeling of respect and fondness for Musicians
			%li
				<span id="def">Statement of Support</span> - Documentation that shows one is in agreement with the idea presented
	.body
		%h3
			The Statement
		%ul
			%li
				I agree to the following:
			%ul
				%li
					I love Musicians 
				%li
					I support Musician Rights 
				%li
					I support The Musician Memo.
	.button.love_button
		I Accept

app/views/pages/_memo.html.haml
.memo.exit_mem.r_box
	.top
		%h1
			Musician Rights Memo
	.body
		.text
			I am joining this movement because I believe that if everyone unites to support the Musician Rights Memo, we will create a new standard in the music industry where MUSICIAN'S COME FIRST!
		%h3
			Definitions:
		%ul
			%li
				<span id="def">Music</span> - A recognizable sound
			%li
				<span id="def">Musician</span> - Anyone who creates a recognizable sound
			%li
				<span id="def">Rights</span> - Inherent entitlement 
			%li
				<span id="def">Musician Rights</span> –  The Right to own and maintain control of one’s Music.  
				%ul
					%li
						The Right to own and control Copyright. 
					%li
						The Right to own and control Master recording.
					%li
						The Right to own and control Publishing.

		%h3
			The Memo
		%ul
			%li
				I agree to the following:
			%ul
				%li
					I will not contract away my Musician Rights at a percentage greater than what I receive. 
				%li
					I will never give more than half of my rights away. 
				%li
					I will only engage opportunities for my music that respects my rights.
				%li
					I WILL NEVER RELINQUISH MY MUSICIAN RIGHTS!
	.button.mem_button
		I Accept
	%i.icon-remove.close

app/views/pages/_pick.html.haml
.pick_bx
	.title
		Are you a..
	.button
		Music Lover
	.button
		Musician

app/views/pages/_twitter.html.erb
<a class="twitter-timeline" href="https://twitter.com/MusicianRights" data-widget-id="360891389875216384">Tweets by @MusicianRights</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/pages/about.html.haml
= render 'layouts/header'
= render 'layouts/nav'
.about
	.pic
		%h2
			Founder
		=image_tag "indiegogoprofilepic.jpg"
		%p
			My name is Davina Amiri and I am an Artist's lawyer based in NY. While representing clients, I have become frustrated with the lack of bargaining power for Artists. 
		%p
			After going to SXSW 2013 and listening to many music experts and panelists, I saw the need for a strong and aggressive representative voice for musicians in the Music Industry. 
	.text
		%h1
			Together We Have a Voice
		.video
			%iframe{:allowfullscreen => "", :frameborder => "0", :height => "315", :src => "//www.youtube.com/embed/65E4vO1WRec", :width => "560"}
		%p
			As new technologies rattle the entire Entertainment Industry, now is especially the time for Musicians to come together. Not at the hands of Corporate created organizations, but from the hands of Musicians and Music lovers as well.
		%p
			This social enterprise will help Musicians regain power in contract negotiations, which means more money for Musicians.
		%p
			We truly believe if Musicians and Music Lover's unite through this organization and Musicians agree to certain minimum requirements for their contracts, Musicians will finally have an equal playing field in the Music Industry.
		%h2
			What Makes Us Different
		%p 
			Musician Rights is different from any other oranizations advocating for musicians, because it starts a movement
			%ol
				%li 
					where musicians agree to fair contract standards
				%li 
					is free of entrenched business interests 
				%li 
					defines Musician Rights
				%li
					unites musicians and music lover's
	%ul
		%a{'href' => '/donate'}
			%li
				%i.icon-usd
				%p
					donate
		%a{'href' => 'mailto:musicanrights.org@gmail.com'}
			%li
				%i.icon-comments
				%p
					contact
		%a{'href' => '/members'}
			%li
				%i.icon-pencil
				%p
					get involved

app/views/pages/donate.html.haml
= render 'layouts/header'
= render 'layouts/nav'
.donate
	.text
		%h1
			Donate to Musician Rights
		%h2
			Thanks for contributing to fund Musician Rights ongoing work!
		%p
			Donating through this page funds our general operations.  
			%br
				You can donate by sending a check to:
		%p
			Musician Rights 
			%br
			349 Fifth Avenue
			%br
			New York, NY 10016
	.paypal_box
		%h3
			Donate via PayPal
		%form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
			%input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
			%input{:name => "hosted_button_id", :type => "hidden", :value => "XMJPLWPRB3JEC"}/
			%input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif", :type => "image"}/
			%img{:alt => "", :border => "0", :height => "1", :src => "https://www.paypalobjects.com/en_US/i/scr/pixel.gif", :width => "1"}/

app/views/pages/home.html.haml
= render 'layouts/header'
= render 'layouts/nav'
.container
	.banner
	.first
		.screen
		.overlay
		.content
			.head
				%h1
					Our Mission
				.mission
					.top
						Uniting Musicians and Music Lovers to change the standard of doing business in the music industry.
					%ul
						.sub_header
							Definition of Musician Rights
						.nest_box
							%li
								Music - A recognizable sound
							%li
								Musician - Anyone who creates a recognizable sound
							%li
								Rights - Inherent entitlement
					%ul
						.sub_header
						.nest_box
							%li
								The Right to own and maintain control of one’s Music.
							%li
								The Right to own and control Copyright.
							%li
								The Right to own and control Master recording.
							%li
								The Right to own and control Publishing.
					%a{'href' => '/members?flash=Sign Up Below to Join the Movement'}
						.member
							Become A Member
			.g_head
				%h1
					Our Goals
				.goals
					%ul.tabs
						%a{:href => "#tab1"} 
							%li Empower
						%a{:href => "#tab2"} 
							%li Educate
						%a{:href => "#tab3"}
							%li Impact
					#tab1
						%p Knowledge is power. Use this site to learn about Musician Rights.
					#tab2
						%p Agree to the Musician Rights Memo or the Music Lover's Statement of Support to create a new standard of doing business in the music industry.
					#tab3
						%p Together we can be apart of any action or debate which would effect musicians.
	.second
		.mid_container
			.memo_one
				.memo
					.banner
						Musician Rights Memo
				%a{:href => "/"}
					.memo_box
						%br
						%br
						%i.icon-headphones
						%p Learn your Rights
		.mid_container
			.mid_box
				.top
					%h3
						Share with the World
					.copy
						%p 
							Click to Download the Musician Rights Logo to Include on Your Personal Site
					%form{:action => "http://everfimkt.s3.amazonaws.com/CSS/Video/logo_three.png", :method => "get"}
						%button{:type => "submit"} 
							=image_tag 'logo_three.png'
		.mid_container
			.memo_two
				.memo
					.banner
						Music Lover's Statement of Support
				%a{:href => "/"}
					.memo_box
						%br
						%br
						%i.icon-file-text-alt
						%p Support the Movement
	.third
		.section_one
			.banner
				Upcoming Events
			.box
				.events
					.text
						- if @events
							-@events.each do |event|
								.event
									.title
										=event.title
									-if event.date
										.date
											- date = event.date
											= date.inspect
											<span class='time'> #{event.time} </span>
									.details
										Event Details:
										.dts
											=event.details
									.location
										=event.location
									%a{"href" => event.button_url}
										.join
											Join Event

		.section_two
			.banner
				Follow Us on Twitter
			.box
				.twitter
					=render 'pages/twitter'
		.section_three
			.banner
				Like Us on Facebook
			.box
				.facebook
					=render 'pages/facebook'
		=render 'pages/memo'
		.home_love
			=render 'pages/lovers'
			%i.icon-remove.close
#fb-root

app/views/pages/members.html.haml
= render 'layouts/header'
.top_copy.expand
	.spacing
		.text
			%h1
				We stand for our members
			%p
				It is common knowledge musicians make substantially less money as compared to the businesses that profit from their music. When musicians first start out, they have very little bargaining power. They are the targets of bad contracts, which sometimes follow them their whole careers. We want Musicians to receive their fair share of the profits from their music.
			%h3
				Membership
			.meme_content	
				.mem_info
					Musicians become members by accepting the Musician Rights memo.
					%br
					%i.icon-circle-arrow-down
				.mem_info.r_second_copy
					Music lover's become members by accepting the Statement of support.
					%br
					%i.icon-circle-arrow-down
		.counter.r_counter
			.count_bx
				.copy
					Total Members
				.count
					=@count
.third
	.lovers
		= render 'pages/lovers'
		.memo_bx
			.top
				%h1
					Musician Rights Memo
				.body
					%div
						I am joining this movement because I believe that if everyone unites to support the Musician Rights Memo, we will create a new standard in the music industry where MUSICIAN'S COME FIRST!
					%h3
						Definitions:
					%ul
						%li
							<span id="def">Music</span> - A recognizable sound
						%li
							<span id="def">Musician</span> - Anyone who creates a recognizable sound
						%li
							<span id="def">Rights</span> - Inherent entitlement 
						%li
							<span id="def">Musician Rights</span> –  The Right to own and maintain control of one’s Music.  
							%ul
								%li
									The Right to own and control Copyright. 
								%li
									The Right to own and control Master recording.
								%li
									The Right to own and control Publishing.

					%h3
						The Memo
					%ul
						%li
							I agree to the following:
						%ul
							%li
								I will not contract away my Musician Rights at a percentage greater than what I receive. 
							%li
								I will never give more than half of my rights away. 
							%li
								I will only engage opportunities for my music that respects my rights.
							%li
								I WILL NEVER RELINQUISH MY MUSICIAN RIGHTS!
	.signup.r_signup_box
		.join.r_header2
			Join The Movement
		.errors
		.messages
			Thank you for signing up!
		= semantic_form_for @new_user, url: users_path, remote: true do |f|
			= f.input :first_name
			= f.input :last_name
			= f.input :email
			= f.input :zipcode, as: :string
			= f.input :band, label: "Band (if applicable)"
			= f.input :opt_out, label: "Exclude your name from being posted on our website"
			= f.action :submit, label: "Next"
	.base	
		.section_one.mem_list
			.box
				.top
					Members
				.copy
					We are building a movement of engaged artists and supporters standing up for musician rights.
					%br
					Here are some of our members
				.events
					.text
						-@users.each do |user|
							.mem_event
								.count
									Member since:
									%br
									=user.created_at.strftime("%b, %Y")
								.first
									=user.first_name
								.last
									=user.last_name
								.band
									- if user.band != ""
										Band: 
										=user.band
		.perk_box
			%h2
				Sweeten The Deal
			.perk
				%p contribute
				%i.icon-usd
				<span id="num">10</span>
				%p 
					You recognize the need for an aggressive Musician Rights Movement. Your donation to MusicianRights.org, will get you an awesome Logo Sticker!
				%form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
					%input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
					%input{:name => "hosted_button_id", :type => "hidden", :value => "XMJPLWPRB3JEC"}/
					%input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif", :type => "image"}/
			.perk
				%p contribute
				%i.icon-usd
				<span id="num">50</span>
				%p 
					You recognize the need for an aggressive Musician Rights Movement. Your donation to MusicianRights.org, will get you an awesome Logo T-shirt!
				%form{:action => "https://www.paypal.com/cgi-bin/webscr", :method => "post", :target => "_top"}
					%input{:name => "cmd", :type => "hidden", :value => "_s-xclick"}/
					%input{:name => "hosted_button_id", :type => "hidden", :value => "XMJPLWPRB3JEC"}/
					%input{:alt => "PayPal - The safer, easier way to pay online!", :border => "0", :name => "submit", :src => "https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif", :type => "image"}/
				
	.user_type
		= @type
	=render 'pages/memo'
	.lovers_popup
		=render 'pages/lovers'
	=render 'pages/pick'

app/views/users/create.html.haml
hi

app/views/users/new.html.haml
.new_user
	= semantic_form_for @user, remote: true do |f|
		= f.inputs
		= f.action :submit, label: "Sign Up"

app/views/users/panel.html.haml
=render 'layouts/header'
- if admin?
	.admin
		.create_event
			= semantic_form_for @new_event, url: events_path, remote: true do |f|
				= f.inputs
				= f.actions :submit
		.current_events
			- @events.each do |event|
				= event.title
				= link_to 'Delete', event_path(event), :confirm => 'Are you sure?', :method => :delete
				%br
			= link_to 'Download All Users', csv_path
- else
	.sorry
		Sorry but you have to be an admin to veiw this page. 
		%br
		If you have admin rights, 
		%a{"href" => "/admin"}
			click here to login.